### ISSUE TITLE
SIGSEGV, Segmentation fault when trying to open a non-zst file

### ISSUE THREAD

**Issue by mxmlnkn** [martinellimarco/indexed_zstd#1]
When opening an .xz file with IndexedZstdFile, in order to check for exceptions, no exceptions is thrown, however when trying to read one byte, it will segfault! This should be detected and an exception should be thrown.

Consider this:
```bash
gdb --args python3 -c '
    from indexed_zstd import IndexedZstdFile
    f = IndexedZstdFile( "tests/simple.xz" )
    print( "Opened File!" )
    f.read( 1 )
'
```

I'll get this output:

```c++
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python3...
(No debugging symbols found in python3)
(gdb) r
Starting program: /usr/bin/python3 -c from\ indexed_zstd\ import\ IndexedZstdFile\;\ f\ =\ IndexedZstdFile\(\ \"tests/simple.xz\"\ \)\;\ print\(\ \"Opened\ File\!\"\ \)\;\ f.read\(\ 1\ \)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Opened File!

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff73dc7d1 in ZSTDSeek_getJumpCoordinate (sctx=sctx@entry=0x9a3ef0, uncompressedPos=1048576) at indexed_zstd/libzstd-seek/zstd-seek.c:192
192	indexed_zstd/libzstd-seek/zstd-seek.c: No such file or directory.
(gdb) bt
#0  0x00007ffff73dc7d1 in ZSTDSeek_getJumpCoordinate (sctx=sctx@entry=0x9a3ef0, uncompressedPos=1048576)
    at indexed_zstd/libzstd-seek/zstd-seek.c:192
#1  0x00007ffff73dcacd in ZSTDSeek_read (sctx=0x9a3ef0, outBuffSize=1048576, outBuff=0x7ffff6dc1010) at indexed_zstd/libzstd-seek/zstd-seek.c:325
#2  ZSTDSeek_read (outBuff=0x7ffff6dc1010, outBuffSize=1048576, sctx=0x9a3ef0) at indexed_zstd/libzstd-seek/zstd-seek.c:319
#3  0x00007ffff73d4bee in ZSTDReader::read (this=<optimized out>, this=<optimized out>, outputFileDescriptor=-1, nBytesToRead=<optimized out>, 
    outputBuffer=<optimized out>) at indexed_zstd/ZSTDReader.hpp:197
#4  __pyx_pf_12indexed_zstd_16_IndexedZstdFile_12readinto (__pyx_v_self=0x7ffff7483f90, __pyx_v_bytes_like=<optimized out>)
    at indexed_zstd/indexed_zstd.cpp:2216
#5  __pyx_pw_12indexed_zstd_16_IndexedZstdFile_13readinto (__pyx_v_self=0x7ffff7483f90, __pyx_v_bytes_like=<optimized out>)
    at indexed_zstd/indexed_zstd.cpp:2152
#6  0x00000000005c4b10 in ?? ()
#7  0x00000000005f4ca1 in ?? ()
#8  0x00000000005f57c0 in PyObject_CallMethodObjArgs ()
#9  0x000000000064db5d in ?? ()
#10 0x000000000064dc32 in ?? ()
#11 0x000000000064f425 in ?? ()
#12 0x0000000000504743 in ?? ()
#13 0x000000000056b399 in _PyEval_EvalFrameDefault ()
#14 0x000000000056955a in _PyEval_EvalCodeWithName ()
#15 0x000000000068c4a7 in PyEval_EvalCode ()
#16 0x000000000067bc91 in ?? ()
#17 0x000000000067bd0f in ?? ()
#18 0x000000000067bf1f in PyRun_StringFlags ()
#19 0x000000000067dc8f in PyRun_SimpleStringFlags ()
#20 0x00000000006b60ec in Py_RunMain ()
#21 0x00000000006b63bd in Py_BytesMain ()
#22 0x00007ffff7dd60b3 in __libc_start_main (main=0x4eea30 <main>, argc=3, argv=0x7fffffffd798, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffd788) at ../csu/libc-start.c:308
#23 0x00000000005fa4de in _start ()
```

**Comment by martinellimarco** [comment]
Thanks for testing this!
It's a regression introduced when I separated the creation of the jump table in libzstd-seek.
I've added a check to read the first frame header. If it's not valid now it doesn't initialize the seek context and the expected exception is thrown.

And.. I've just discovered that github close the issue automatically if the commit message have the word "fix" follower by the issue number.

This weekend I'm going to stress test this library. I have a lot of edge cases including corrupted zstd files, files that starts with valid frames and are followed by garbage and so on.

**Comment by mxmlnkn** [comment]
Thanks for the fast fix. Seems to work now.

> And.. I've just discovered that github close the issue automatically if the commit message have the word "fix" follower by the issue number.

"Closes" should also work but I think it only actually closes it, if you push it to your main branch, i.e., by default "master". So you can push commits like this to the develop branch and on merging the pull request, the issue gets closed.

**Comment by martinellimarco** [comment]
> So you can push commits like this to the develop branch and on merging the pull request, the issue gets closed.
Nice, I didn't know that. I'm going to test it the next time, thanks!
